insert into passports(code, number) values (1, 1);
insert into passports(code, number) values (2, 2);
insert into passports(code, number) values (3, 3);
insert into passports(code, number) values (4, 4);
insert into passports(code, number) values (5, 5);
insert into passports(code, number) values (6, 6);
insert into passports(code, number) values (7, 7);
insert into employee (first_name, last_name, position, salary, age, passport_id) values ('John', 'Smith', 'Developer', 10000, 30   , 1);
insert into employee (first_name, last_name, position, salary, age, passport_id) values ('Adam', 'Hamilton', 'Developer', 12000, 35, 2);
insert into employee (first_name, last_name, position, salary, age, passport_id) values ('Tracy', 'Smith', 'Architect', 15000, 40  , 3);
insert into employee (first_name, last_name, position, salary, age, passport_id) values ('Lucy', 'Kim', 'Developer', 13000, 25     , 4);
insert into employee (first_name, last_name, position, salary, age, passport_id) values ('Peter', 'Wright', 'Director', 50000, 50  , 5);
insert into employee (first_name, last_name, position, salary, age, passport_id) values ('Alan', 'Murray', 'Developer', 20000, 37  , 6);
insert into employee (first_name, last_name, position, salary, age, passport_id) values ('Pamela', 'Anderson', 'Analyst', 7000, 27 , 7);